# Security configuration
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${HOST_IP_ADDRESS:localhost}:9000
                    jwk-set-uri: http://${HOST_IP_ADDRESS:localhost}:9000/oauth2/jwks

eureka:
    client:
        service-url:
            defaultZone: http://${HOST_IP_ADDRESS:localhost}:9999/eureka/
    instance:
        prefer-ip-address: true
#        ip-address: ${HOST_IP_ADDRESS:localhost}:8082

# Expose all the Actuator endpoints
management:
    endpoints:
        web:
          exposure:
            include: "*"
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true
            
# Logging configuration
logging:
    level:
        root: INFO
    file:
        name: gateway-service.log
    logback:
        rollingpolicy:
            max-file-size: 2MB
    pattern:
        correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    include-application-name: false




