eureka:
    client:
        service-url:
            defaultZone: http://${HOST_IP_ADDRESS:localhost}:9999/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true

# Expose all the Actuator endpoints
management:
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true
            
# Logging configuration
logging:
    level:
        root: INFO
    file:
        name: gateway-service.log
    logback:
        rollingpolicy:
            max-file-size: 2MB
    pattern:
        correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    include-application-name: false




