# Data Source
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-spring-cloud.c5igmqq2495t.ap-southeast-1.rds.amazonaws.com:3306/auth_service
    username: seminar
    password: seminar01

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update