spring:
  cloud:
    gateway:
      routes:
        - id: product-service-api
          uri: lb://product-service
          predicates:
            - Path=/product-service/(?<segment>.*)
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/product-service/(?<segment>.*), /${segment}

        - id: order-service-api
          uri: lb://order-service
          predicates:
            - Path=/order-service/(?<segment>.*)
            - Method=POST,GET,PUT,DELETE
          filters:
            - RewritePath=/order-service/(?<segment>.*), /${segment}

        - id: user-service-api
          uri: lb://user-service
          predicates:
            - Path=/user-service/(?<segment>.*)
            - Method=POST,GET,PUT,DELETE
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}